drop TABLE MAGAZZINO cascade constraints;
drop TABLE ORDINI cascade constraints;
drop TABLE MOVIMENTI cascade constraints;
drop TABLE PRENOTAZIONI cascade constraints;
drop TABLE PRODOTTI cascade constraints;
drop TABLE PRODOTTIORDINATI cascade constraints;
drop SEQUENCE ORDINI_SEQ;
drop SEQUENCE PRENOTAZIONI_SEQ;

CREATE TABLE  MOVIMENTI (CODICEPRODOTTO VARCHAR2(10), QTA NUMBER(5,0), CAUSALE VARCHAR2(10), TIME NUMBER(25,0));
CREATE TABLE  MAGAZZINO (CODICE VARCHAR2(10), NOME VARCHAR2(30), CATEGORIA VARCHAR2(20), SOTTOCATEGORIA VARCHAR2(20), TIPO VARCHAR2(30), DESCRIZIONE VARCHAR2(30), PREZZO NUMBER(10,0), RISERVATOAZIENDA VARCHAR2(10));
CREATE TABLE ORDINI (IDORDINE NUMBER(5) NOT NULL, DATAORDINE DATE NOT NULL, STATO VARCHAR2(20) NOT NULL, DATAARRIVO DATE NOT NULL, CODCLIENTE NUMBER(5) NOT NULL, CONSTRAINT ORDINI_PK PRIMARY KEY (IDORDINE));
CREATE SEQUENCE  ORDINI_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER  BI_ORDINI before insert on ORDINI for each row  begin if :NEW.IDORDINE is null then select ORDINI_SEQ.nextval into :NEW.IDORDINE from dual; end if; end;; 
CREATE TABLE PRENOTAZIONI (IDPRENOTAZIONE NUMBER(5) NOT NULL, CODPRODOTTO VARCHAR2(12), CODCLIENTE NUMBER(5), DATAPRENOTAZIONE DATE, DATAARRIVO DATE, QTA NUMBER(5), CONSTRAINT PRENOTAZIONI_PK PRIMARY KEY (IDPRENOTAZIONE));
CREATE SEQUENCE  PRENOTAZIONI_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER  BI_PRENOTAZIONI before insert on PRENOTAZIONI for each row  begin if :NEW.IDPRENOTAZIONE is null then select PRENOTAZIONI_SEQ.nextval into :NEW.IDPRENOTAZIONE from dual; end if; end;; 
CREATE TABLE PRODOTTI (CODICEPRODOTTO NUMBER(5) NOT NULL, NOME VARCHAR2(30) NOT NULL, DESCRIZIONE VARCHAR2(150) NOT NULL, TIPO CHAR(8) NOT NULL, RISERVATOAZIENDA NUMBER(1) NOT NULL, CODICECATEGORIA NUMBER(5) NOT NULL, CODICESOTTOCATEGORIA NUMBER(5) NOT NULL, CONSTRAINT PRODOTTI_PK PRIMARY KEY (CODICEPRODOTTO));
CREATE TABLE PRODOTTIORDINATI (CODORDINE NUMBER(5) NOT NULL, CODPRODOTTO VARCHAR2(25) NOT NULL, QTAORDINATA NUMBER(5) NOT NULL, IVA NUMBER(3) NOT NULL, PREZZO NUMBER(10,2) NOT NULL, SCONTO NUMBER(3) NOT NULL, CONSTRAINT PRODOTTIORDINATI_PK PRIMARY KEY (CODORDINE, CODPRODOTTO));
-- Gruppo g1 (definitivo)
drop TABLE AMMINISTRATORI cascade constraints;
drop TABLE APPUNTAMENTI cascade constraints;
drop SEQUENCE AMMINISTRATORI_SEQ;
CREATE TABLE AMMINISTRATORI (IDADMIN NUMBER(6,0), NOME VARCHAR2(25) NOT NULL ENABLE, COGNOME VARCHAR2(25) NOT NULL ENABLE, PASSWORD NVARCHAR2(16) NOT NULL ENABLE, MAIL VARCHAR2(50) NOT NULL ENABLE,  CONSTRAINT AMMINISTRATORI_PK PRIMARY KEY (IDADMIN) ENABLE);
CREATE SEQUENCE  AMMINISTRATORI_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER BI_AMMINISTRATORI  before insert on AMMINISTRATORI for each row begin if :NEW.IDADMIN is null then select AMMINISTRATORI_SEQ.nextval into :NEW.IDADMIN from dual; end if; end;;
CREATE TABLE APPUNTAMENTI (DATA TIMESTAMP (1) NOT NULL ENABLE, IDADMIN NUMBER(5,0) NOT NULL ENABLE, DESCRIZIONE VARCHAR2(250), CODICECLIENTE NUMBER(5,0) NOT NULL ENABLE, CONSTRAINT APPUNTAMENTI_PK PRIMARY KEY (DATA, IDADMIN) ENABLE);
-- Gruppo g2 (definitivo)

drop TABLE AZIENDE cascade constraints;
drop TABLE PRIVATI cascade constraints;
drop TABLE CLIENTI cascade constraints;
drop SEQUENCE CLIENTI_SEQ;
CREATE TABLE  CLIENTI    (	CODCLIENTE NUMBER(5,0) NOT NULL ENABLE,	CODCONFERMA CHAR(16),	TELEFONO VARCHAR2(13) NOT NULL ENABLE,	PASSWORD VARCHAR2(16) NOT NULL ENABLE,	MAIL VARCHAR2(50) NOT NULL ENABLE,	VIA VARCHAR2(60) NOT NULL ENABLE,	CAP NUMBER(5,0) NOT NULL ENABLE,	SCALA VARCHAR2(2),	PIANO NUMBER(3,0),	CITTA VARCHAR2(20) NOT NULL ENABLE,	PROVINCIA CHAR(2) NOT NULL ENABLE,	PAESE VARCHAR2(20) NOT NULL ENABLE,	ATTIVO NUMBER(1,0) NOT NULL ENABLE,	 CONSTRAINT CLIENTI_PK PRIMARY KEY (CODCLIENTE) ENABLE,	 CONSTRAINT CLIENTI_CON UNIQUE (MAIL) ENABLE   ) ;
CREATE SEQUENCE   CLIENTI_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER  BI_CLIENTI  before insert on CLIENTI                for each row begin    if :NEW.CODCLIENTE is null then    select CLIENTI_SEQ.nextval into :NEW.CODCLIENTE from dual; end if; end;;
CREATE TABLE PRIVATI (CODICEFISCALE CHAR(16) NOT NULL, NOME VARCHAR2(20) NOT NULL, COGNOME VARCHAR2(20) NOT NULL, CODCLIENTE NUMBER(5) NOT NULL, CONSTRAINT PRIVATI_PK PRIMARY KEY (CODICEFISCALE), CONSTRAINT PRIVATI_FK FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTI (CODCLIENTE) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE);
CREATE TABLE AZIENDE (PIVA NUMBER(11) NOT NULL, CODCLIENTE NUMBER(5) NOT NULL, RAGIONESOCIALE VARCHAR2(20) NOT NULL, CONSTRAINT AZIENDE_PK PRIMARY KEY (PIVA), CONSTRAINT AZIENDE_FK FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTI (CODCLIENTE) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE);


-- comuni --
drop table COMUNI;
drop table PROVINCIE;
drop table REGIONI;
drop table STATE;

CREATE TABLE  COMUNI (ID NUMBER(5,0) NOT NULL ENABLE, NOME VARCHAR2(50) NOT NULL ENABLE, IDPROVINCIA NUMBER(4,0) NOT NULL ENABLE, IDREGIONE NUMBER(4,0) NOT NULL ENABLE, CATASTO VARCHAR2(5), CONSTRAINT COMUNI_PK PRIMARY KEY (ID) ENABLE);
CREATE TABLE  PROVINCIE (IDPROVINCIA NUMBER(4,0) NOT NULL ENABLE, NOMEPROVINCIA VARCHAR2(20) NOT NULL ENABLE, IDREGIONE NUMBER(4,0) NOT NULL ENABLE, SIGLAPROVINCIA CHAR(2), CONSTRAINT PROVINCE_PK PRIMARY KEY (IDPROVINCIA) ENABLE);
CREATE TABLE  REGIONI (IDREGIONE NUMBER(4,0) NOT NULL ENABLE, NOMEREGIONE VARCHAR2(50) NOT NULL ENABLE, CONSTRAINT REGIONI_PK PRIMARY KEY (IDREGIONE) ENABLE);
CREATE TABLE  STATE (STATEID NUMBER(*,0), LASTNAME VARCHAR2(255), FIRSTNAME VARCHAR2(255), ADDRESS VARCHAR2(255), CITY VARCHAR2(255));


-- categorie e sottocategorie
drop table CATEGORIA;
drop table SOTTOCATEGORIAABBIGLIAMENTO;
drop table SOTTOCATEGORIAINFORMATICA;
drop table SOTTOCATEGORIASPORT;

CREATE TABLE CATEGORIA (ID NUMBER(5,0), NAME VARCHAR2(20) NOT NULL ENABLE, PATHIMMAGINE VARCHAR2(50) NOT NULL ENABLE, PRIMARY KEY (ID) ENABLE);
CREATE TABLE SOTTOCATEGORIAABBIGLIAMENTO (ID NUMBER(5,0), PATHIMMAGINE  VARCHAR2(190) NOT NULL ENABLE, NAMECATEGORIA VARCHAR2(100), NAMESUBCATEGORIA VARCHAR2(100), PRIMARY KEY (ID) ENABLE);
CREATE TABLE SOTTOCATEGORIAINFORMATICA (ID NUMBER(5,0), NAME VARCHAR2(20) NOT NULL ENABLE, PATHIMMAGINE VARCHAR2(120) NOT NULL ENABLE, PRIMARY KEY (ID) ENABLE);
CREATE TABLE  SOTTOCATEGORIASPORT(ID NUMBER(5,0), PATHIMMAGINE VARCHAR2(120) NOT NULL ENABLE, NAMESUBCATEGORIA VARCHAR2(100), NAMECATEGORIA  VARCHAR2(100), PRIMARY KEY (ID) ENABLE);

INSERT INTO categoria (ID,NAME,PATHIMMAGINE) VALUES (1,'Abbigliamento','assets/img/categorie/abbigliamento.png');
INSERT INTO categoria (ID,NAME,PATHIMMAGINE) VALUES (2,'Sport','assets/img/categorie/sport.png');
INSERT INTO categoria (ID,NAME,PATHIMMAGINE) VALUES (3,'Informatica','assets/img/categorie/informatica.png');
INSERT INTO categoria (ID,NAME,PATHIMMAGINE) VALUES (4,'Elettronica','assets/img/categorie/elettronica.png');


INSERT INTO SOTTOCATEGORIAABBIGLIAMENTO (ID,PATHIMMAGINE,NAMECATEGORIA) VALUES (1,'http://localhost:8081/assets/img/sottoCategoriaAbbigliamento/uomo.png','Abbigliamento');
INSERT INTO SOTTOCATEGORIAABBIGLIAMENTO (ID,PATHIMMAGINE,NAMECATEGORIA) VALUES (2,'http://localhost:8081/assets/img/sottoCategoriaAbbigliamento/donna.png','Abbigliamento');
INSERT INTO SOTTOCATEGORIAABBIGLIAMENTO (ID,PATHIMMAGINE,NAMECATEGORIA) VALUES (3,'http://localhost:8081/assets/img/sottoCategoriaAbbigliamento/bambino.png','Abbigliamento');


INSERT INTO SOTTOCATEGORIASPORT (ID,PATHIMMAGINE,NAMESUBCATEGORIA,NAMECATEGORIA) VALUES (1,'http://localhost:8081/assets/img/sottoCategoriaSport/tennis.png','Tennis','Sport');


INSERT INTO SOTTOCATEGORIAINFORMATICA (ID,NAME,PATHIMMAGINE) VALUES (1,'Software','http://localhost:8081/assets/img/sottoCategoriaInformatica/informatica.png');


